/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "whugsryjrtdxhmearwwx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodWdzcnlqcnRkeGhtZWFyd3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4ODU5NzgsImV4cCI6MjA4NzQ2MTk3OH0.zG-FUG6fiwTPClYJmOJNVLqps5--kBFbHb7i6xKFAHY"